apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: fluent-bit
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: fluent-bit
    version: 2.1.0
  #values:
    