apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: istiocontrolplane
spec:
  profile: default
  values:
    mixer:
      adapters:
        prometheus:
          enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
